/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#554430",
        "surface-bright": "#fcf8fa",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#44474a",
        "tertiary-container": "#261908",
        "surface-container": "#f0edee",
        "primary-fixed-dim": "#c0c6d8",
        "on-surface-variant": "#45474c",
        "tertiary": "#000000",
        "tertiary-fixed-dim": "#dcc2a8",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "outline": "#76777c",
        "on-secondary-fixed": "#191c1f",
        "primary-container": "#151c29",
        "surface": "#fcf8fa",
        "surface-dim": "#dcd9da",
        "surface-container-low": "#f6f3f4",
        "primary": "#121926",
        "secondary": "#5c5f62",
        "on-primary-fixed-variant": "#404756",
        "background": "#fcf8fa",
        "secondary-fixed-dim": "#c4c7ca",
        "on-primary-fixed": "#151c29",
        "on-background": "#1b1b1c",
        "on-primary-container": "#7d8494",
        "tertiary-fixed": "#f9dec3",
        "inverse-primary": "#c0c6d8",
        "on-primary": "#ffffff",
        "surface-variant": "#e5e2e3",
        "surface-container-high": "#eae7e8",
        "inverse-surface": "#303031",
        "outline-variant": "#c6c6cc",
        "on-surface": "#1b1b1c",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dce2f5",
        "secondary-container": "#dee0e4",
        "inverse-on-surface": "#f3f0f1",
        "on-tertiary-fixed": "#261908",
        "surface-tint": "#585e6e",
        "on-tertiary-container": "#968069",
        "error-container": "#ffdad6",
        "on-secondary-container": "#606366",
        "surface-container-highest": "#e5e2e3",
        "secondary-fixed": "#e0e2e6",
        "on-secondary": "#ffffff",
        "accent-gold": "#D4AF37",
        "accent-pink": "#ff85a1"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "xs": "0.5rem",
        "md": "1.5rem",
        "lg": "2.5rem",
        "xl": "4rem",
        "sm": "1rem",
        "gutter": "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-sm": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
